### ISSUE TITLE
Faction Seach broken

### ISSUE THREAD

**Issue by Lukas11112000** [WesternGamer/AddMissingSearchBoxes#1]
There seems to be a problem with the search function in the Faction-Tab.
The searchbox still exists but entering any characters does not do anything.
I am running on Linux but at least three other players running on Win10 have the same problem.

**Comment by WesternSpace** [comment]
I am not as active in SE modding lately, so it may take a while for this to get fixed.

**Comment by Lukas11112000** [comment]
Thanks for the reply, it's nice to know this is not abandoned.
The Plugin has been great so far and has given us sooo much QoL, it's sad that code changes broke it :/
I hope you have an easy troubleshooting process, take your time.

**Comment by WesternSpace** [comment]
Should be fixed in the update that has been pushed out and after avaness approves it. 

Will close this issue after you test and find nothing is wrong.

**Comment by Lukas11112000** [comment]
Very nice!
It's again working as it should, thanks for the quick fix :+1:

**Comment by WesternSpace** [comment]
Fix verified, closing.
